name: Build and Deploy
on: 
  push:
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v5
        with:
          lfs: true

      - name: Install and Build ğŸ”§
        run: |
          sudo apt update && sudo apt install reprepro #python3 python3-pip python3-mako

          cd package_server

          # import keys
          gpg2 --import package_server/pub.gpg
          echo -e "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --import --no-tty --batch --yes
          
          mkdir incoming
          cp ../packages/*/*/* incoming/

          reprepro -V processincoming default
          reprepro -V export

          #mv dists package_server
          #mv pool package_server
          #mv deploy/deploy-disclaimer.md deploy/README.md

          #python3 createStaticDirectoryListing.py deploy --indexPage README.md

      - name: Deploy ğŸš€
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: package_server
          folder: deploy