name: Build and Deploy
on: 
  push:
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v5
        with:
          lfs: true

      - name: Install and Build ðŸ”§
        run: |
          sudo apt update && sudo apt install reprepro #python3 python3-pip python3-mako

          cd package_server

          # import keys
          gpg2 --import pub.gpg
          echo -e "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --import --no-tty --batch --yes
          
          mkdir incoming

          if [ -n "$(find ../packages -type f -name '*.deb' 2>/dev/null)" ]; then
            cp ../packages/*/*/* incoming/
            reprepro -V processincoming default
          else
            echo "No packages found, skipping processincoming"
          fi
          
          reprepro -V export

          #mv dists package_server
          #mv pool package_server
          #mv deploy/deploy-disclaimer.md deploy/README.md

          #python3 createStaticDirectoryListing.py deploy --indexPage README.md

      - name: Deploy ðŸš€
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: package_server
          folder: deploy